# Generated by Django 3.0a1 on 2019-10-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
