# Generated by Django 3.0a1 on 2019-12-09 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_diary_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='diary',
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
